server:
  address: 0.0.0.0
  port: 8081

spring:
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ./files
  mail:
    host: smtp.gmail.com
    port: 587
    username: seoja250502@gmail.com
    password: iqhx rity tyrq qene
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

oci:
  config:
    file: /home/opc/.oci/config
    profile: DEFAULT
  namespace: axs1tvst9t3n
  bucket: bucket-20250606-0153
  region: ap-chuncheon-1
  bucket-public: false

logging:
  level:
    root: INFO

firebase:
  database-url: https://aico-1853c.firebaseio.com