server:
  port: 8081

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ./files
  mail:
    host: smtp.gmail.com
    port: 587
    username: seoja250502@gmail.com
    password: iqhx rity tyrq qene
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO

firebase:
  database-url: https://aico-1853c.firebaseio.com